src/app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('tests/', include('testify.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/testify/urls.py
from django.urls import path

from testify.views import TestListView, TestDetailView, TestRunnerView, QuestionView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),

]

src/testify/models.py
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from accounts.models import User
from core.models import BaseModel


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.name}'


class Test(models.Model):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)
    # description = models.TextField(max_length=512, null=True, blank=True)

    def __str__(self):
        return f'{self.text}'


class Answer(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='answers', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class TestResult(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='test_results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='test_results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)

    score = models.DecimalField(default=0.0, decimal_places=2, max_digits=5,
                                validators=[MinValueValidator(0), MaxValueValidator(100)])

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(Question.ANSWER_MAX_LIMIT)]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(Question.ANSWER_MAX_LIMIT)]
    )
    current_order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])

    def __str__(self):
        return f'{self.test} ran by {self.user.get_full_name()} at {self.write_date}'

    def time_spent(self):
        time_spent = self.write_date - self.create_date
        return time_spent - datetime.timedelta(microseconds=time_spent.microseconds)

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    # def best_result(self):
    #     result = TestResult.objects.extra(select={
    #         'points': self.points},
    #         order_by=['points']).first()
    #     return result

src/testify/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, ModelForm, modelformset_factory


from testify.models import Answer, Question


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

    def clean(self):
        pass


class AnswerForm(ModelForm):
    is_selected = forms.BooleanField(required=False)
    # test = fields.CharField()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['text'].label = ""
        self.fields['is_selected'].label = ""

    class Meta:
        model = Answer
        fields = ['text', 'is_selected']
        widgets = {
            'text': forms.TextInput(attrs={'readonly': True})
        }


AnswerFormSet = modelformset_factory(
    model=Answer,
    form=AnswerForm,
    extra=0
)


class QuestionsInlineFormSet(BaseInlineFormSet):

    def clean(self):  # проверяем количество вопросов берем из models 
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError('Quantity of questions is out of range ({}..{})'.format(
                self.instance.QUESTION_MIN_LIMIT, self.instance.QUESTION_MAX_LIMIT
            ))

        # counters = [question.order_number for question in self.instance.questions.all()]
        lst = [form.cleaned_data['order_number'] for form in self.forms]
        lst.sort()
        check = [i for i in range(1, len(lst) + 1)]
        if lst != check: 
            raise ValidationError('Order number must be within limits ')


class AnswerInlineFormSet(BaseInlineFormSet):

    def clean(self):  # проверяем количество ответов
        if not (self.instance.ANSWER_MIN_LIMIT <= len(self.forms) <= self.instance.ANSWER_MAX_LIMIT):
            raise ValidationError('Quantity of answers is out of range ({}..{})'.format(
                self.instance.ANSWER_MIN_LIMIT, self.instance.ANSWER_MAX_LIMIT
            ))

        num_correct_answers = sum([
            1
            for form in self.forms
            if form.cleaned_data['is_correct']
        ])

        if num_correct_answers == 0:
            raise ValidationError('At LEAST one answer must be correct!')

        if num_correct_answers == len(self.forms):
            raise ValidationError('Not allowed to select ALL answers!')

        

src/testify/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls.base import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views import View
from accounts.models import User

from testify.forms import AnswerFormSet
from testify.models import Question, Test, TestResult

from django.contrib import messages


# Create your views here.


class TestListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    model = Test
    template_name = 'tests-list.html'
    context_object_name = 'tests'
    paginate_by = 5


class TestDetailView(LoginRequiredMixin, DetailView):
    model = Test
    template_name = 'details.html'
    context_object_name = 'test'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['continue_flag'] = TestResult.objects.filter(
            user=self.request.user,
            test=self.get_object(),
            state=TestResult.STATE.NEW,

        ).count()
        #  Записываем QuerrySet в словарь по ключу last_run, 
        context['last_run'] = TestResult.objects.filter(
            user=self.request.user,
            test=self.get_object(),
            state=TestResult.STATE.FINISHED,

        ).order_by('-write_date').first()

        context['best_result'] = TestResult.objects.filter(test=self.get_object()).extra(select={'points': 'num_correct_answers - num_incorrect_answers', 'duration': 'write_date - create_date'}, order_by=['-points', 'duration']).first()        
        context['results'] = TestResult.objects.filter(
            user=self.request.user,
            test=self.get_object(),
        ).order_by('-write_date')
        context['open_run'] = TestResult.objects.filter(
            user=self.request.user,
            test=self.get_object(),
            state=TestResult.STATE.NEW,
        ).first()

        return context


class TestRunnerView(LoginRequiredMixin, View):

    def get(self, request, id):
        current_user_tests = TestResult.objects.filter(
            user=request.user,
            test=Test.objects.get(id=id),
            state=TestResult.STATE.NEW
        )
        if current_user_tests.count() == 0:
            TestResult.objects.create(
                user=request.user,
                state=TestResult.STATE.NEW,
                test=Test.objects.get(id=id),
                num_correct_answers=0,
                num_incorrect_answers=0,
                current_order_number=1,
            )

        return redirect(reverse('tests:next', args=(id,)))


class QuestionView(LoginRequiredMixin, View):
    def get(self, request, id):
        # test_result = get_object_or_404(TestResult.objects.filter(
        #     user=request.user,
        #     test=Test.objects.get(id=id),
        #     state=TestResult.STATE.NEW
        # ))

        test_results = TestResult.objects.filter(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
        )
        if test_results.count() == 0:
            return redirect(reverse('tests:details', args=(id,)))

        test_result = test_results.first()

        order_number = test_result.current_order_number
        question = Question.objects.get(test__id=id, order_number=order_number)
        answers = question.answers.all()
        form_set = AnswerFormSet(queryset=answers)

        return render(
            request=request,
            template_name='question.html',
            context={
                'question': question,
                'form_set': form_set,
            }
        )

    def post(self, request, id):
        # test_result = get_object_or_404(TestResult.objects.filter(
        #     user=request.user,
        #     test=Test.objects.get(id=id),
        #     state=TestResult.STATE.NEW
        # ))

        test_results = TestResult.objects.filter(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
        )
        if test_results.count() == 0:
            return redirect(reverse('tests:details', args=(id,)))

        test_result = test_results.first()

        order_number = test_result.current_order_number
        question = Question.objects.get(test__id=id, order_number=order_number)
        answers = question.answers.all()
        form_set = AnswerFormSet(data=request.POST)
        show_result = test_result.user.show_result

        possible_choices = len(form_set.forms)
        selected_choices = [

            'is_selected' in form.changed_data
            for form in form_set.forms
        ]

        correct_choices = sum(
            answer.is_correct == choice
            for answer, choice in zip(answers, selected_choices)
        )

        point = int(correct_choices == possible_choices)

        test_result = TestResult.objects.get(
            user=request.user,
            test=question.test,
            state=TestResult.STATE.NEW
        )

        test_result.num_correct_answers += point
        test_result.num_incorrect_answers += (1 - point)
        test_result.current_order_number += 1
        test_result.save()
        if show_result is True: 
            if point == 1:
                messages.info(request, 'Well done, correct answer')
            else:
                messages.warning(request, 'Incorrect answer')

        if order_number == question.test.questions.count():
            test_result.state = TestResult.STATE.FINISHED
            test_result.save()

            User.objects.filter(
                username=request.user,
            ).update(rating=request.user.rating + test_result.points())

            return render(
                request=request,
                template_name='finish.html',
                context={
                    'test_result': test_result,
                    # 'time_spent': test_result.write_date - test_result.create_date,
                    'test_result_score': test_result.num_correct_answers / test_result.test.questions.count() * 100

                }
            )
        else:
            return redirect(reverse('tests:next', args=(id,)))

src/testify/templates/details.html
{% extends 'base.html' %}

{% block header %}
    <h1>{{ test }}</h1>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Test info</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Description</td>
                        <td>{{ test.description }}</td>
                      </tr>
                      <tr>
                        <td>Num of questions</td>
                        <td>{{ test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Num of runs</td>
                        <td>{{ test.test_results.count }}</td>
                      </tr>
                      <tr>
                        <td>Best result</td>
                        <td>{{ best_result.points}},({{ best_result.user }})</td>
                      </tr>
                      <tr>
                        <td>Last run</td>
                        <td>{{last_run.write_date}}</td>
                      </tr>
                      {% if open_run.test %}
                      <tr>
                        <td>Current open run</td>
                        <td>{{open_run.write_date}}</td>
                      </tr>
                      {% endif %}
                    </tbody>
                  </table>
            </div>
            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{{ test.image.url }}">
                </div>

                {% if continue_flag %}

                <div class="d-flex justify-content-center mt-5 mb-5" >
                        <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-warning">CONTINUE ▶️</a>
                </div>

                {% else %}
                <div class="d-flex justify-content-center mt-5 mb-5" >
                  <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-success">START ▶️</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>
    <table class="table table-striped">
          <tr>
              <th>No.</th>
              <th>User</th>
              <th>Started</th>
              <th>Time spent</th>
              <th>Points</th>
          </tr>
      {% for result in results %}
          <tr>
              <td>{{ result.id }}</td>
              <td>{{ result.user }}</td>
              <td>{{ result.write_date }}</td>
              <td>{{ result.taken_time }}</td>
              <td>{{ result.points }}</td>
          </tr>
      {% endfor %}
  </table>
  
{% endblock %}

src/testify/templates/finish.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
    <h1>You passed test</h1>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>{{ test_result.test.title }}</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Correct answers</td>
                        <td>{{ test_result.num_correct_answers }} / {{ test_result.test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Points</td>
                        <td>{{ test_result.points }}%</td>
                      </tr>

                      <tr>
                        <td>Score</td>
                        <!-- <td>{{ test_result_score|floatformat:2 }}%</td> -->
                        <td>{% with test_result_score|floatformat:2 as progress %}
                          <div class="progress">
                              <div class="progress-bar " role="progressbar" style="width:{{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">{{ test_result_score|floatformat:2 }}%</div>
                          </div>
                          {% endwith %}</td>
                      </tr>
                      <tr>
                        <td>Time spent</td>
                        <td>{{ test_result.time_spent }}</td>
                      </tr>
                      <tr>
                        <td>Time finished</td>
                        <td>{{ test_result.write_date }}</td>
                      </tr>
                    </tbody>
                  </table>
            </div> 
            <div class="col-sm">

                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{% static 'testify\img\finish.jpg' %}">
                </div>

                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a href="{% url 'tests:list' %}" type="button" class="btn-lg btn-success">START ANOTHER TEST ▶️</a>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

src/testify/templates/question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load math_funcs %}

{% block header %}
     {% include 'includes/messages.html' %}
    <h1>Question: {{ question.text }}?</h1>
    {% with question.order_number|add:-1|div:question.test.questions.count|mult:100 as progress %}
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width:{{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    {% endwith %}
    
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form_set.management_form}}

        Current Question #{{ question.order_number }}/{{ question.test.questions.count }}

        {% for form in form_set %}
            <!-- {{ form|crispy }} -->
            <div class="mt-1">
                {{ form.is_selected }} <label >  {{ form.text.value }}</label>
            </div>              

        {% endfor %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

src/testify/templates/tests-list.html
{% extends 'base.html' %}

{% block title %}
    <title>Tests List</title>
{% endblock %}

{% block header %}
<header>
    <strong><p>Tests List</p></strong>
</header>
{% endblock %}

{% block content %}

{% include 'includes/tests-table.html' %}

{% endblock %}