src/accounts/urls.py
from accounts.views import (AccountCreateView, AccountLoginView, 
                            AccountLogoutView, AccountPasswordView, 
                            AccountUpdateView, LeadersListView)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register', AccountCreateView.as_view(), name='register'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordView.as_view(), name='password'),
    path('list', LeadersListView.as_view(), name='list'),
]

src/app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('tests/', include('testify.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),  

]

src/accounts/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(default='default.png', upload_to='pics')
    rating = models.DecimalField(default=0.0, decimal_places=2, max_digits=5,
                                 validators=[MinValueValidator(0), MaxValueValidator(100)])
    show_result = models.BooleanField("Show results popup", default=False)

src/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from accounts.models import User


class AccountCreateForm(UserCreationForm):
  
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'show_result', 'image']


class AccountUpdateForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'show_result', 'image']

src/accounts/views.py
# import datetime
from django.views.generic.list import ListView
from accounts.forms import (AccountCreateForm, 
                            AccountUpdateForm)

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views.generic import CreateView 
from django.views.generic.edit import UpdateView

from accounts.models import User
from testify.models import TestResult


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')  # это редирект после завершения регистрации

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User successfully created')
        return result


class AccountLoginView(LoginView):
    model = User
    template_name = 'login.html'
    success_url = reverse_lazy('link')

    # функция ниже переправляет на страницу откужа пришел пользователь
    # Если сработал LoginRequiredMixin

    def get_redirect_url(self):
        if self.request.GET.get('next'):  # это параметр Get запроса проверяет, есть ли 
            return self.request.GET.get('next')  # next в адресной строке
        return reverse('core:index')

    def form_valid(self, form):

        result = super().form_valid(form)
        messages.info(self.request, f'User {self.request.user} logged in!')

        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'
    
    def get(self, request, *args, **kwargs):
        result = super().get(request, *args, **kwargs)
        messages.info(self.request, f'User {self.request.user} has been logged out!')
        return result


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('core:index')
    context_object_name = 'user' 
    # pk_url_kwarg = 'pk'
    
    def get_object(self, queryset=None):
        return self.request.user
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tests'] = TestResult.objects.filter(user=self.request.user).order_by('write_date')
        return context


class AccountPasswordView(LoginRequiredMixin, PasswordChangeView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'password.html'
    success_url = reverse_lazy('link')  


class LeadersListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    model = User
    template_name = 'leaders-list.html'
    # context_object_name = 'users'
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all().order_by('-rating')
        return context

src/accounts/templates/leaders-list.html
{% extends 'base.html' %}

{% block title %}
    <title>Leaderboard</title>
{% endblock %}

{% block header %}
<header>
    <strong><p>Leaderboard</p></strong>
</header>
{% endblock %}


{% block content %}

{% include 'includes/leaders-table.html' %}

{% endblock %}

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block header %}
<header>
    <p>Login</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
  
        <input class="btn btn-success" type="submit" value="Login">
        <a class = "btn btn-sm " href="{% url 'core:index' %}">Home</a>
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Logout</title>
{% endblock %}

{% block header %}
<header>
    <p>User is Logged Out</p>
</header>
{% endblock %}

{% block content %}
          
        <a class = "btn btn-sm " href="{% url 'accounts:login' %}">Login</a>
        <a class = "btn btn-sm " href="{% url 'core:index' %}">Home</a>
{% endblock %}

src/accounts/templates/password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Change Password</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}
        {{form|crispy}}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Edit user</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
         
        <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.image.url }}">
            </div>
    
            <div class="media-body  p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
    

        {% csrf_token %}
       
        {{form|crispy}}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
        <a class="btn btn-light" href="{% url 'accounts:password' %}">Change Password</a>
    </form>

   
    <table class="table table-striped">
        <tr>
            
            <th>Test Name</th>
            <th>Test Date</th>
            <th>Test Points</th>
            
        </tr>
    {% for test in tests %}
        <tr>
            <td>{{ test.test }}</td>
            <td>{{ test.write_date }}</td>
            <td>{{ test.points }}</td>
            
        </tr>
    {% endfor %}

    </table>


{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Register new user</title>
{% endblock %}

{% block header %}
<header>
    <p>Login</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        
        <input class="btn btn-success" type="submit" value="Register">
        <a class = "btn btn-sm " href="{% url 'core:index' %}">Home</a>
    </form>
{% endblock %}