src/accounts/urls.py
from accounts.views import (AccountCreateView, AccountLoginView, 
                            AccountLogoutView, AccountPasswordView, 
                            AccountUpdateView, LeadersListView)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register', AccountCreateView.as_view(), name='register'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordView.as_view(), name='password'),
    path('list', LeadersListView.as_view(), name='list'),
]

src/app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('tests/', include('testify.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),  

]

src/testify/urls.py
from django.urls import path

from testify.views import TestListView, TestDetailView, TestRunnerView, QuestionView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),

]

src/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <!-- <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
  <title>Testify</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
</style>
</head>

<body>
    {% block title %}
    <title>Testify</title>
    {% endblock %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'core:index' %}">Testify</a></h5>
        <nav class="my-2 my-md-0 mr-md-3">

         
          <a class="mr-2 p-2 text-dark" href="{% url 'tests:list' %}">List of tests</a>
          <a class="mr-2 p-2 text-dark" href="{% url 'accounts:list' %}">Leadersboard</a>
          <a class="mr-2 p-2 text-dark" href="{% url 'admin:index' %}">Settings</a>
          

        </nav>
   
         <!-- {{ user  }} -->

         <a class="mr-2" href="{% url 'accounts:profile' %}">{{ user  }}</a>

         {% if user.is_authenticated %}
           
          <div class="img-circle.vert">
          <!-- <img class="rounded-circle p-1 m-1" width="40" height="40"  src="{{ user.profile.image.url }}"> -->
          </div>

            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:profile' %}">Profile({{ user }})</a>
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:logout' %}">Logout</a>
         {% else %}
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:login' %}">Sign In</a>
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:register' %}">Register</a>
         {% endif %}

        
      </div>
    
    <div class="container">
    <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
      
    {% block header %}
    
    <header>
      {% include 'includes/messages.html' %}

      
      <strong><p>Welcome to Testify</p></strong>
    </header>
    {% endblock %}
    </div>   

    

    {% block content %}

    {% endblock %}

  </div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Main Pages</title>
{% endblock %}

{% block content %}

<div class="container">
  <div class="card-deck mb-3 text-center">

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Tests</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'tests:list' %}">List of tests</a></h1>
        </div>
    </div>

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Leaders</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'accounts:list' %}">Leadersboard</a></h1>
        </div>
    </div>


    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Index</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'core:index' %}">Index</a></h1>
        </div>
    </div>

    </div>
  </div>
  

{% endblock %}